name: Build and Push to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Azure Container Registry
        run: echo ${{ secrets.AZURE_REGISTRY_PASSWORD }} | docker login ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }} -u ${{ secrets.AZURE_REGISTRY_USERNAME }} --password-stdin

      - name: Build Product Service Image
        run: docker build -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/product-service:latest ./backend/productService

      - name: Push Product Service Image
        run: docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/product-service:latest

      - name: Build User Service Image
        run: docker build -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/user-service:latest ./backend/userService

      - name: Push User Service Image
        run: docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/user-service:latest

      - name: Build Frontend Image
        run: docker build --build-arg VITE_API_GATEWAY_URL=${{ secrets.VITE_API_GATEWAY_URL }} -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/frontend:latest ./frontend

      - name: Push Frontend Image
        run: docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/frontend:latest

      - name: Build API Gateway Image
        run: docker build -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/api-gateway:latest ./backend/apiGateway

      - name: Push API Gateway Image
        run: docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/api-gateway:latest

      #payment service
      - name: Build Payment Service Image
        run: docker build -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/payment-service:latest ./backend/paymentService

      - name: Push Payment Service Image
        run: docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/payment-service:latest