name: Build and Push to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Azure Container Registry
        run: echo ${{ secrets.AZURE_REGISTRY_PASSWORD }} | docker login ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }} -u ${{ secrets.AZURE_REGISTRY_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/product-service:latest ./backend/productService

      - name: Push Docker Image
<<<<<<< Updated upstream
        run: docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/product-service:latest
=======
        run: docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/product-service:latest

      - name: Build Frontend Image
        run: docker build -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/frontend:latest ./frontend

      - name: Push Frontend Image
        run: docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/frontend:latest
>>>>>>> Stashed changes
